version: '3'
services:
  twint:
    build: .
    container_name: twint

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: twint_elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    restart: always
    ports:
      - "${ES_PORT}:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: twint_kibana
    restart: always
    ports:
      - "${KIBANA_PORT}:5601"

volumes:
  esdata01:
    driver: local

networks:
  default:
    external:
      name: nw_twint
